[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 9

[terminal]
shell = { program = "/bin/zsh" }

[colors.primary]
background = "#000000"

[colors.normal]
black = "#000000"
red = "#444444"
green = "#C7C7C7"
yellow = "#4C4C4C"
blue = "#585858"
magenta = "#646464"
cyan = "#6B6B6B"
white = "#B1B1B1"

[colors.bright]
black = "#7B7B7B"
red = "#3B3B3B"
green = "#C7C7C7"
yellow = "#4C4C4C"
blue = "#585858"
magenta = "#646464"
cyan = "#6B6B6B"
white = "#B1B1B1"


[window]
padding = { x = 2, y = 2 }
